name: Project video
on:
  push:
    branches:
      - main
jobs:
  create-video:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v2
      - name: Research Project Action
        uses: Jonas-D-M/Research-Project@84b1e6e0ee0a3b90069f59a1627a9fd507718313

